# Generated by Django 6.1 on 2026-08-15

from django.db import migrations, models


def copiar_professor_para_m2m(apps, schema_editor):
    """Copia o professor responsável (FK) para o novo campo M2M."""
    Classe = apps.get_model('core', 'Classe')
    for classe in Classe.objects.all():
        if classe.professor_id:
            classe.professores.add(classe.professor_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='professores',
            field=models.ManyToManyField(
                blank=True,
                help_text='Selecione até 4 professores para a classe.',
                related_name='classes',
                to='core.professor',
                verbose_name='Professores',
            ),
        ),
        migrations.RunPython(
            copiar_professor_para_m2m, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='classe',
            name='professor',
        ),
    ]
