# Generated by Django 6.1 on 2026-08-18 19:04

from django.conf import settings
from django.db import migrations, models


def _normalizar_nome(nome):
    import re
    import unicodedata
    if not nome:
        return ''
    s = unicodedata.normalize('NFKD', str(nome))
    s = ''.join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r'\s+', ' ', s)
    return s.strip().casefold()


def normalizar_nomes_existentes(apps, schema_editor):
    Aluno = apps.get_model('core', 'Aluno')
    for aluno in Aluno.objects.all():
        aluno.nome_normalizado = _normalizar_nome(aluno.nome)
        aluno.save(update_fields=['nome_normalizado'])


def reverter_normalizacao(apps, schema_editor):
    Aluno = apps.get_model('core', 'Aluno')
    Aluno.objects.all().update(nome_normalizado='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno_atualizado_por_aluno_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_normalizado',
            field=models.CharField(db_index=True, default='', editable=False, help_text='Nome sem acentos/caixa, usado para impedir duplicatas na mesma classe.', max_length=120, verbose_name='Nome normalizado'),
            preserve_default=False,
        ),
        migrations.RunPython(
            normalizar_nomes_existentes, reverter_normalizacao
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(fields=('nome_normalizado', 'classe'), name='aluno_unico_nome_normalizado_por_classe'),
        ),
    ]
