# Generated by Django 6.1 on 2026-08-18 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aluno_nome_normalizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateField(db_index=True, verbose_name='Data'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['aula', 'presente'], name='idx_presenca_aula_presente'),
        ),
    ]
